## Original File MIT License Copyright (c) 2024 TinyTakinTeller
class_name MenuButtonEnum

enum ID {
	UNKNOWN,
	MAIN_MENU_PLAY,
	MAIN_MENU_OPTIONS,
	MAIN_MENU_CREDITS,
	MAIN_MENU_QUIT,
	OPTIONS_MENU_BACK,
	OPTIONS_MENU_RESET,
	CREDITS_MENU_BACK,
	SAVE_FILES_MENU_BACK
}
